package domain

import "errors"

var (
	ErrInvalidAirportCode      = errors.New("invalid airport code")
	ErrInvalidAirportCity      = errors.New("invalid airport city")
	ErrAirportExists           = errors.New("airport already exists")
	ErrAirportNotFound         = errors.New("airport not found")
	ErrInvalidAirplaneCode     = errors.New("invalid airplane code")
	ErrInvalidSeatCapacity     = errors.New("invalid seat capacity")
	ErrAirplaneExists          = errors.New("airplane already exists")
	ErrAirplaneNotFound        = errors.New("airplane not found")
	ErrInvalidRouteCode        = errors.New("invalid route code")
	ErrInvalidRouteAirports    = errors.New("invalid route airports")
	ErrRouteExists             = errors.New("route already exists")
	ErrRouteNotFound           = errors.New("route not found")
	ErrInvalidScheduleRoute    = errors.New("invalid schedule route")
	ErrInvalidScheduleAirplane = errors.New("invalid schedule airplane")
	ErrInvalidScheduleDate     = errors.New("invalid schedule date")
	ErrInvalidScheduleID       = errors.New("invalid schedule id")
	ErrScheduleExists          = errors.New("schedule already exists")
	ErrScheduleNotFound        = errors.New("schedule not found")
	ErrInvalidPassengerName    = errors.New("invalid passenger name")
	ErrInvalidBookingReference = errors.New("invalid booking reference")
	ErrInvalidSeatNumber       = errors.New("invalid seat number")
	ErrInvalidBookingStatus    = errors.New("invalid booking status")
	ErrBookingExists           = errors.New("booking already exists")
	ErrBookingNotFound         = errors.New("booking not found")
	ErrFlightFull              = errors.New("flight fully booked")
)
